name: flutter_application_1
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  ## 상태관리
  flutter_riverpod: ^2.4.9
  riverpod_annotation: 2.3.3
  riverpod_generator: 2.3.9

  ## utils
  go_router: ^12.1.1
  build_runner: 2.3.3
  json_serializable: 6.6.2
  freezed: ^2.4.6
  http: ^0.13.6
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  path_to_regexp: ^0.4.0
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  logger: ^2.0.2+1

  ## UI
  flutter_svg: ^2.0.9
  lottie: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

## assets 자동생성
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/
    - lib/assets/lottie/
    - lib/assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: lib/design_system/text/fonts/Pretendard-Black.ttf
          weight: 900
        - asset: lib/design_system/text/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: lib/design_system/text/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: lib/design_system/text/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: lib/design_system/text/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: lib/design_system/text/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: lib/design_system/text/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: lib/design_system/text/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: lib/design_system/text/fonts/Pretendard-Thin.ttf
          weight: 100
